---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections: 
upload_dir: ".vuepress/public"
public_path: ".vuepress/public"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
